### ISSUE TITLE
Improve GUI to not redraw screen every time the cursor is moved

### ISSUE THREAD

**Issue by SerLizar** [astronautlevel2/StarUpdater#10]
Old 3ds — a9lh — version cia 1.3 of the updater — have latest luma hourly

Every time I press the d-pad to go up or down an option the screen goes to black for a moment.
(I'm assuming it's do to you needing to redraw what's onscreen and the o3ds not being fast enough for me not to notice)

**Comment by astronautlevel2** [comment]
I'm working on a solution for this next release. You're correct about having to redraw the entire screen as of right now, hopefully I'll be able to find a way around that.

**Comment by astronautlevel2** [comment]
Fixed in https://github.com/astronautlevel2/StarUpdater/commit/59781125bf3ba59b0ebb42283bfc1fb464c7733e
