### ISSUE TITLE
Updating to Wrong Version Bug

### ISSUE THREAD

**Issue by cheatfreak47** [astronautlevel2/StarUpdater#15]
I left the title kind of vague because the bug is rather strange and hard to explain.

Luma3DS v5.5 just released today, and I attempted to switch from the unstable build (which includes the commit in the version) to the stable, and doing so, it seems to switch me to v5.4-859944dc, which is not the latest stable, and is, in fact, not the stable branch at all.

However, when I chose unstable, it then updated me to the latest stable build without the commit in the version, so I'm not exactly what the cause of this, possibly something server side? ¯_(ツ)_/¯

**Comment by astronautlevel2** [comment]
Almost definitely something server side. Downloading the latest release from my site manually gives me v5.4-859944dc.

Probably something borked with lastVer checking. Either that or Aurora commited something weirdly and caused my (rather hacky) lastVer checking to fail.

I'll fix it manually for now and close this, I'd prefer this issue to be re-opened on my site's github.
