### ISSUE TITLE
"Update the updater" function attempts to download the CIA version when launched from 3dsx, then crashes.

### ISSUE THREAD

**Issue by Rust-and-Sunset** [astronautlevel2/StarUpdater#17]
Title says it all, really- it crashes to an alternating Red/Black blinking screen.

The program shouldn't be trying to download the CIA version when it's running the .3dsx version via Homebrew Launcher! 

(In case it matters- I'm loading it via GridLauncher, rather than Homebrew Launcher.)

**Comment by astronautlevel2** [comment]
Installing a CIA from a .3dsx won't work as it doesn't have enough permissions. I have no plans to support .3dsx releases going forward.

**Comment by astronautlevel2** [comment]
Re-opening this because apparently there's enough want for a .3dsx version.

**Comment by gnmmarechal** [comment]
I'm going to look into this next.
