### ISSUE TITLE
[Suggestion] Possibility to update payloads

### ISSUE THREAD

**Issue by suzsuzuki** [astronautlevel2/StarUpdater#32]
his is not an issue, but a suggestion. I think will be fine if there's a way to update the default payloads (Decrypt9, Hourglass9 and EmuNAND9) used in Plailect guide. Do you think it's possible?

**Comment by astronautlevel2** [comment]
Something like that already exists: https://github.com/LiquidFenrir/MultiUpdater

**Comment by suzsuzuki** [comment]
thanks
