### ISSUE TITLE
Get stables from Luma3DS releases page

### ISSUE THREAD

**Issue by Pikm** [astronautlevel2/StarUpdater#33]
Downloading the latest Luma3DS update using StarUpdater causes my o3DS to boot to a black screen. Another user with this problem is found [here](https://www.reddit.com/r/3dshacks/comments/4zrjb1/luma3ds_v611_released_with_a_125_second_speed/d6y7yaz)

**Comment by exegg** [comment]
I did a MD5 check of the downloaded file. The arm9loaderhax.bin isn't the same from the Luma3DS 6.1.1 release. Lumaupdater gets the correct file. With Starupdater it gets corrupted somehow or the source is different.

EDIT: Yes. StarUpdater gets the latest release from here https://astronautlevel2.github.io/Luma3DS/ not from the official source. Can this be fixed? Latest hourlies are fine to download from there, but latest stable releases should be the ones from AuroraWright's Github page.

**Comment by astronautlevel2** [comment]
Yeah, my server was using an outdated version of ctrulib which caused a build issue. This affected StarUpdater as well. It's now resolved.

@exegg, Although I agree that getting the latest official release from AW's github page is a good idea, that's easier said than done and I don't have enough time or motivation to work on it right now.

If anyone else would like to implement it and open a PR, I'll be happy to merge it.

**Comment by gnmmarechal** [comment]
Huh. Dealing with GitHub's API is a pain iirc. It probably would be better to make an auto running PHP script to fetch the latest release to your server, but even then... GitHub doesn't have such a thing as a latest release link.

**Comment by astronautlevel2** [comment]
Actually, it does: https://api.github.com/repos/aurorawright/luma3ds/releases/latest

If you can figure out how to parse the JSON using lpp-3ds, it shouldn't be terribly difficult, but I don't believe there's a way to parse JSON using lpp-3ds.

**Comment by Ryuzaki-MrL** [comment]
Yes, [there is](http://dkolf.de/src/dkjson-lua.fsl/home).

**Comment by gnmmarechal** [comment]
Huh, didn't know that.

**Comment by gnmmarechal** [comment]
Then the best way would be to handle it server-side? I guess?

**Comment by gnmmarechal** [comment]
Hum. This doesn't seem like a very good idea now that I take a look at it.

The script would have to parse the JSON, but I have no idea how it'd identify the 7z files (dev and non dev) properly.

Or maybe I'm just too dumb for this.

**Comment by Ryuzaki-MrL** [comment]
There are two objects on the assets array of the JSON object. Each one having a "browser_download_url" pointing to "Luma3DSv6.1.2-dev.7z" and "Luma3DSv6.1.2.7z", respectively. It should be enough.

**Comment by astronautlevel2** [comment]
Indeed, all you'd need to do is check if the name of the download contains "dev" in it or not and get the respective URLs.

**Comment by gnmmarechal** [comment]
This would only work if I trusted the files will ALWAYS be named like that.

**Comment by Ryuzaki-MrL** [comment]
That's why you should be fetching the "browser_download_url", this way it would only depend on the order of the packages (which is ALWAYS the same in each release)

**Comment by astronautlevel2** [comment]
Unfortunately there's not an easy way to extract 7zip files from Lua, so this can't work.
