### ISSUE TITLE
StarUpdater throws an Error Message

### ISSUE THREAD

**Issue by acidpandas** [astronautlevel2/StarUpdater#54]
StarUpdater Error: [string "?"]:55: -1018822656

Haven't checked for updates for Luma3DS in a month. The last time I updated was a month ago, during which time I also updated AL9H using the 3ds.guide steps.

Not sure what's up, and as always thanks for making StarUpdater.

**Comment by kyubix** [comment]
I'm also having the same issue,
StarUpdater Error:[string "?"]:55: 219676672
Reinstalling the StarUpdater doesn't fix the problem

**Comment by astronautlevel2** [comment]
The server that used to serve version information, etc. is down. Therefore, StarUpdater will no longer work.

I highly advise you move on to a better updater, like the fantastic [LumaUpdate](https://github.com/Hamcha/lumaupdate) by @Hamcha
