### ISSUE TITLE
Updater not downloading 7.1 commits

### ISSUE THREAD

**Issue by Dimensional** [astronautlevel2/StarUpdater#55]
The updater isn't able to download from your autobuild repo due to the fact B9Strap now needs another tool to compile Luma. One of the requirements is to get a properly setup python environment to run the require firmtool.

In the event you're having trouble getting it set up, just download some of the python requirements from https://pypi.python.org. For instance, I wasn't able to get python cryptography to work until I manually downloaded and installed the latest versions of cffi, six, and pycparser. Once I got it installed, compiling worked perfectly.

**Comment by astronautlevel2** [comment]
This isn't an issue with StarUpdater, but instead with my autobuild system. I'm already aware of it and working on it (fixing the build part was easy, but holy crap was the bash script used in the build script was horrifying and I'm rewriting it). There's already an issue about it: https://github.com/astronautlevel2/Luma3DS/issues/6

Also, I have to say this, I don't support StarUpdater anymore and I don't know how much longer it'll work and recommend you change to a new program.

**Comment by ihaveamac** [comment]
"I don't support StarUpdater anymore and I don't know how much longer it'll work and recommend you change to a new program." you can hide the issues tab to prevent new ones from being posted.
