### ISSUE TITLE
Self updating... updater?

### ISSUE THREAD

**Issue by Ann0ying** [astronautlevel2/StarUpdater#7]
What about including self-updater into the updater himself?

If it's not possible to replace files while app is working, maybe it's possible to download a .cia that you can install later through FBI, et cetera.

**Comment by astronautlevel2** [comment]
I've been working on that today with little luck, when I realized...

![image](https://cloud.githubusercontent.com/assets/7305572/15276843/7c5127ba-1ac1-11e6-87d7-d44f26317202.png)

It'll be out soon :D

**Comment by astronautlevel2** [comment]
Added in https://github.com/astronautlevel2/StarUpdater/commit/57b6b3d7cecee87381d25488ca7aefd83a4deb48
