### ISSUE TITLE
CIA Install - Error String 52 arithmetic on a nil value

### ISSUE THREAD

**Issue by KHShadowrunner** [astronautlevel2/StarUpdater#8]
I downloaded and went through with installing the CIA version of the app, however when I run it it throws an error saying:

Error: [string "?"]:52: attempt to perform arithmetic on a nil value (local 'offset').

Any suggestions?

**Comment by KHShadowrunner** [comment]
Disregard, I'm 99% sure I know what the problem is :)

**Comment by astronautlevel2** [comment]
I believe this is an issue caused when an arm9loaderhax.bin exists but it isn't your luma payload. You can fix this by creating a config file pointing to your actual luma payload. Next release shouldn't crash when this happens though.
