### ISSUE TITLE
Update the updater currently "updates" to a previous version

### ISSUE THREAD

**Issue by SerLizar** [astronautlevel2/StarUpdater#9]
Old 3ds — a9lh — version cia 1.3 of the updater — have latest luma hourly

I selected the update the updater option to see if it worked, it apparently does most of it correctly even as a cia, downloaded and installed a cia version of itself, only problem was when I opened it back up, I had an older version of the program.

**Comment by astronautlevel2** [comment]
I blame github webpages for not updating the CIA when I uploaded a new version to my github site.

I'll resolve it manually this time, will look into a better solution going forward. 

Thanks for letting me know.

**Comment by astronautlevel2** [comment]
Most recent commit/hotfix release should fix it, but I haven't tested it (don't have my 3ds on me atm). Could you do that?

**Comment by astronautlevel2** [comment]
Fixed in https://github.com/astronautlevel2/StarUpdater/commit/59781125bf3ba59b0ebb42283bfc1fb464c7733e
